# Generated by Django 4.1.4 on 2023-08-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="name",
            field=models.CharField(default="unknown", max_length=200),
            preserve_default=False,
        ),
    ]
